// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugzpidwcwzaxseguxbjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnenBpZHdjd3pheHNlZ3V4YmprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2OTIxNzEsImV4cCI6MjA3MzI2ODE3MX0.vid_wW6SnM-LdZN9ifk5FQwBH3V88s6HAbA3tToCLZ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});